apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: amrelzahar/products:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGODB_HOST
              value: "mongodb.default"
          ports:
            - containerPort: 3000
